xymon_base_url: http://xymon.infra.local
bp: R291bWIhQDA5
hosts:
  ent: enterprise_production
  stg: enterprise_integration
  q: qa
services:
  ondemand: ondemand_v2
  core: core_v2
  cms: cms_v2
  backend: backend_v2
  mplaces: mplaces
  releases: releases
  filecache_server: filecache-server
  syslog: syslog
